apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.metadata.namespace }}
data:
  NODE_ENV: {{ .Values.environment.node_env }}
  RUN_ENV: {{ .Values.environment.run_env }}
  APPDYNAMICS_CONTROLLER_HOST_NAME: "carvana.saas.appdynamics.com"
  APPDYNAMICS_CONTROLLER_PORT: "443"
  APPDYNAMICS_CONTROLLER_SSL_ENABLED: "true"
  APPDYNAMICS_AGENT_ACCOUNT_NAME: "carvana"
  APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "s78ag4dg3ebi"
  APPDYNAMICS_AGENT_APPLICATION_NAME: {{ .Values.appdynamics.applicationname }}
  APPDYNAMICS_AGENT_TIER_NAME: {{ .Chart.Name }}

