export const makesById = {
  audi: 4,
  buick: 7,
  daewoo: 11,
  eagle: 14,
  geo: 17,
  gmc: 16,
  isuzu: 22,
  jaguar: 23,
  jeep: 24,
  lexus: 27,
  maserati: 61,
  maybach: 56,
  'mercedes-benz': 31,
  nissan: 35,
  porsche: 41,
  ram: 783,
  saab: 43,
  suzuki: 48,
  'aston-martin': 54,
  bmw: 5,
  dodge: 13,
  genesis: 897,
  hyundai: 20,
  infiniti: 21,
  kia: 25,
  'land-rover': 26,
  mclaren: 799,
  oldsmobile: 36,
  toyota: 49,
  volkswagen: 50,
  bentley: 57,
  chrysler: 10,
  ferrari: 397,
  honda: 18,
  lincoln: 28,
  lotus: 55,
  mazda: 30,
  mercury: 32,
  'rolls-royce': 58,
  saturn: 44,
  srt: 849,
  subaru: 47,
  volvo: 51,
  acura: 2,
  'alfa-romeo': 3,
  cadillac: 8,
  chevrolet: 9,
  fiat: 430,
  fisker: 840,
  ford: 15,
  freightliner: 867,
  hummer: 19,
  lamborghini: 59,
  mini: 29,
  mitsubishi: 34,
  plymouth: 39,
  pontiac: 40,
  scion: 45,
  smart: 507,
  tesla: 834
};

export const makesList = [
  'acura',
  'aston-martin',
  'alfa-romeo',
  'audi',
  'bentley',
  'bmw',
  'buick',
  'cadillac',
  'chevrolet',
  'chrysler',
  'daewoo',
  'dodge',
  'eagle',
  'ferrari',
  'fiat',
  'fisker',
  'ford',
  'freightliner',
  'genesis',
  'geo',
  'gmc',
  'honda',
  'hyundai',
  'infiniti',
  'isuzu',
  'jaguar',
  'jeep',
  'kia',
  'lamborghini',
  'land-rover',
  'lexus',
  'lincoln',
  'lotus',
  'maserati',
  'maybach',
  'mazda',
  'mclaren',
  'mercedes-benz',
  'mercury',
  'mini',
  'mitsubishi',
  'nissan',
  'oldsmobile',
  'plymouth',
  'pontiac',
  'porsche',
  'ram',
  'rolls-royce',
  'saab',
  'saturn',
  'scion',
  'smart',
  'srt',
  'subaru',
  'suzuki',
  'tesla',
  'toyota',
  'hummer',
  'volkswagen',
  'volvo'
];
